# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: Start a container with nginx
# ====================================

---

- name: Start a container with nginx
  docker_container:
    name: "nginx{{ ansible_host }}"
    image: "nginx:latest"
    ports:
      - "8080:80"
