# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: tasks for delete security groups
# ====================================

---
# delete security groups rules
- name: delete security groups rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: absent
  loop: '{{ security_groups }}'

# delete security groups 
- name: delete security groups 
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: absent
  loop: '{{ security_groups }}'
