# Common vars
availability_zone: melbourne-qh2-uom
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/grp-22-key
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Volume
volumes:
  - vol_name: instance-1-vol
    vol_size: 100
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024
  - vol_name: instance-2-vol
    vol_size: 100
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024
  - vol_name: instance-3-vol
    vol_size: 100
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024
  - vol_name: instance-4-vol
    vol_size: 100
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024

# Security group
security_groups:
  - name: grp-ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: grp-http
    description: "Security group for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: grp-couchdb
    description: "Security group for CouchDB access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: grp-websapp
    description: "Security group for Flask access"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['instance-1-vol']
    instance_flavor: uom.mse.1c4g
  - name: instance-2
    volumes: ['instance-2-vol']
    instance_flavor: uom.mse.2c9g
  - name: instance-3
    volumes: ['instance-3-vol']
    instance_flavor: uom.mse.2c9g
  - name: instance-4
    volumes: ['instance-4-vol']
    instance_flavor: uom.mse.2c9g

# Ubuntu 20.04
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: grp-22-key
