# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: set up couchdb cluster
# ====================================

---
- name: setup cluster
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{couchdb_port}}/_cluster_setup
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\", \"port\": \"{{couchdb_port}}\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['all'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['othernodes'] }}"

- name: add nodes
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{couchdb_port}}/_cluster_setup
    status_code: 201,409
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['othernodes'] }}"

- name: to avoid an error message when finishing
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{couchdb_port}}/
    status_code: 200
    method: GET
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes


- name: finish cluster
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"finish_cluster\"}"
    headers:
      Content-Type: "application/json"
