# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: tasks for creating instances
# ====================================


- include_tasks: openstack-volume.yaml
- include_tasks: openstack-security-group.yaml
- include_tasks: openstack-instance.yaml