# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: create volumes
# ====================================

---
# Create volumes from vars
- name: Create volume(s) on NeCTAR
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# Get a list of volume Ids from the return value of os_volume
- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."