# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 22 - Assignment 2
# Ran Liang 1162222
# Yulun Huang 910398
# Yubo Sun 1048638
# Yanhao Wang 1142087
# Xindi Fang 749394
# Last Updated: 2021-05-25
# Description: front end deployment tasks
# ====================================

---
- name: Change ownership, group and permissions
  become: yes
  file:
    path: /home/ubuntu/COMP90024/
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0777
    
- name: copy frontend file
  become: yes
  copy:
    src: ../frontend.tgz
    dest: /home/ubuntu/COMP90024/
    owner: root
    group: root
    mode: 0777
    
- name: unzip
  raw: tar -xzf /home/ubuntu/COMP90024/frontend.tgz -C /home/ubuntu/COMP90024/
  
- name: install dependencies
  become: yes
  pip:
    name: ['flask', 'couchdb', 'numpy', 'pandas', 'gunicorn']
    state: latest
  
- name: run frontend 
  raw: cd /home/ubuntu/COMP90024/frontend/; gunicorn  --workers=20 -D app:app -b 0.0.0.0:5000
  