- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/anaconda3/bin/python
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    
- hosts: all
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true

  roles:
    - role: set-proxy
    - role: setup-docker