- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true

  roles:
    - role: openstack-common
  tasks:
    - name: compress the folder
      raw: cd ../; tar czpvf frontend.tgz frontend
    
- hosts: frontend
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true
  become: yes
  become_method: sudo
  tasks:
    - name: Change ownership, group and permissions
      file:
        path: /home/ubuntu/COMP90024/
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: 0777
        
    - name: copy frontend file
      copy:
        src: ../frontend.tgz
        dest: /home/ubuntu/COMP90024/
        owner: root
        group: root
        mode: 0777
        
    - name: unzip
      raw: tar -xzf /home/ubuntu/COMP90024/frontend.tgz -C /home/ubuntu/COMP90024/
