- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/anaconda3/bin/python
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images # could delete
    - role: create_instances