- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true
  
- hosts: harvester
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - role: deploy_harvester
    