---
- hosts: localhost
  vars_files:
    - host_vars/instances_config.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: remove-instances
    - role: remove-volumes
    - role: remove-security-groups
